### ISSUE TITLE
Support Slack OpenAPI v2 spec

### ISSUE THREAD

**Issue by atroche** [wafflespeanut/paperclip#102] opened 2019-09-18 06:45 UTC
Pending issues after triage:
- [x] `additionalProperties` is currently a schema, but it's either a boolean or a schema. If it's a boolean and set to `true`, then we have to collect `SomeMap<String, any>`, and if it's `false`, we should enforce that objects with unspecified properties are invalid. We could also support an edge case when it's not set at all, at which point we ignore the fields (this way, we can skip deserializing unnecessary fields).
---

Hello! Cool project.

Apologies if I'm jumping the gun here, but when I tried this:
`paperclip --api v2 -o gen_slack https://raw.githubusercontent.com/slackapi/slack-api-specs/master/web-api/slack_web_openapi_v2.json`

I got this:

`error: Invalid value for '<spec>': JSON error: data did not match any variant of untagged enum SchemaRepr at line 20 column 10 `

The v2 validator in [swagger-cli](https://github.com/APIDevTools/swagger-cli) seems to think it's a valid schema.

I'm guessing full support for OpenAPI v2 is still WIP?

Side note: is there a good / easy way to get more information from Serde about what failed in the parsing? I couldn't work out from that error message what led to its being unable to deserialize.

**Comment by wafflespeanut** [comment] 2019-09-18 18:44
> I'm guessing full support for OpenAPI v2 is still WIP?

You're right that v2 is still in WIP. The next release (0.4.0) will have full swagger support for clients.

> Is there a good / easy way to get more information from Serde about what failed in the parsing?

I think we have to extrapolate from the line and column numbers. I think the problem is with `additionalProperties` (in the 7th line). Swagger supports specifying both objects and boolean, but we only [support objects](https://paperclip.waffles.space/paperclip/v2/struct.DefaultSchema.html#structfield.extra_props) at this point.

Thank you for filing this! :smile:

**Comment by wafflespeanut** [comment] 2020-04-18 16:37
I shouldn't have assumed that Slack API is correct :sweat_smile: It turns out that it's actually incorrect. The `items` field [must be an object](https://github.com/OAI/OpenAPI-Specification/blob/c5e9a8a703f40da5d5a1a63dc1ff7530263eca4f/schemas/v2.0/schema.json#L1109) according to Swagger's modification of JSON schema. [The editor](https://editor.swagger.io/) also fails to parse the spec. Then, I checked OpenAPI v3, and apparently [this syntax is not allowed](https://swagger.io/docs/specification/data-models/data-types/#mixed-array) in v3 either (see "mixed array"), so I'm gonna remove the existing feature where we relax a bit on the `items` field whilst parsing the schema.

Also, now that one bug has been resolved and the other is invalid, I'm gonna close this issue. Thank you for reporting this! :smile:

**Closed by wafflespeanut** 2020-04-18 16:37 UTC
Labels: bug
